unit CosTasti;  (* variabili e costanti pto critico *)

interface
uses crt;

const

(* caratteri speciale ed Fkeys  *)

nul  =#0;
bs   =#8;
bel  =#7;
ff   =#12;
cr   =#13;
esc  =#27;
home =#199;
fine =#207;
sin  =#75;
des  =#77;
su   =#72;
giu  =#80;
PgUp =#73;
PgDn =#81;
del  =#008;
ins  =#210;

f1   =#59;
f2   =#188;
f3   =#189;
f4   =#190;
f5   =#191;
f6   =#192;
f10  =#196;


implementation

begin
end.
