 Unit PASLOGOT;    {Unit… per il LOGO di presentazione del DIMOT,
                    distanza minima tra orbita asteroide e Terra}

 Interface

 Uses Crt;

  Procedure Icona;

 Implementation

  Procedure Icona;
   Begin
writeln;
writeln('  ²²²²²²²²          ²²        ²²          ²²        ²²²²²²²²²²       ²²²²²²²²²²');
writeln('  ²²      ²²        ²²        ²²²        ²²²        ²²      ²²           ²²    ');
writeln('  ²²       ²²       ²²        ²² ²      ² ²²        ²²      ²²           ²²    ');
writeln('  ²²        ²²      ²²        ²²   ²   ²  ²²        ²²      ²²           ²²    ');
writeln('  ²²        ²²      ²²        ²²     ²    ²²        ²²      ²²           ²²    ');
writeln('  ²²        ²²      ²²        ²²          ²²        ²²      ²²           ²²    ');
writeln('  ²²       ²²       ²²        ²²          ²²        ²²      ²²           ²²    ');
writeln('  ²²      ²²        ²²        ²²          ²²        ²²      ²²           ²²    ');
writeln('  ²²²²²²²²          ²²        ²²          ²²        ²²²²²²²²²²           ²²    ');
writeln;
writeln(' ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿');
writeln(' ³     ®D.I.M.O.T.¯ Š l`acronimo di "Distanza di Intersezione Minima con      ³');
writeln(' ³ (da un`idea di P.Sicoli del-      l`Orbita della Terra"                    ³');
writeln(' ³  l`Osservatorio di Sormano)               Nome Programma: PASDIMOT.EXE     ³');
writeln(' ³                                          Il programma determina la Minima  ³');
writeln(' ³ Il file dati PASDIMOT.DAT Š a Campi     Distanza tra 2 Curve nello Spazio: ³');
writeln(' ³ FISSI e numero di Records(Corpi Ce-    cioŠ tra l`orbita di un Corpo Cele- ³');
writeln(' ³ lesti) ILLIMITATO. In ordine questi   ste (asteroide, cometa, etc.) e la   ³');
writeln(' ³ sono i 5 Elementi Orbitali necessa-  traiettoria della Terra.              ³');
writeln(' ³ ri: w, ê, i, e, a.                                                         ³');
writeln(' ³            Ing. Giuseppe Matarazzo (Mag.97) - tel: 0931/945259             ³');
writeln(' ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ');
  End;
END.
